version: '3.3'

services:
  app:
    build: ./
    ports:
      - "8081:8081"
    depends_on:
      - database
    environment:
      PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_LIQUIBASE_URL: jdbc:postgresql://database:5432/postgres
      SPRING_LIQUIBASE_USER: postgres
      SPRING_LIQUIBASE_PASSWORD: postgres
  database:
    image: postgres:alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  liquibase:
    image: liquibase/liquibase:4.23.1
    container_name: liquibase
    depends_on:
      - database
    volumes:
      - ./src/main/resources/liquibase/changelog/:/liquibase/changelog/
    command: --defaultsFile=/liquibase/changelog/liquibase.docker.properties update