server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    auto-commit: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

#spring.datasource.auto-commit=false
    properties:
      hibernate:
        default_schema: public
        generate_statistics: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog/liquibase.docker.properties

  main:
    allow-circular-references: true

app:
  jwt:
    secret: "404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970"
    expiration: 86400000

  configuration:
    threadPoolTaskExecutor:
      corePoolSize: 50
      maxPoolSize: 50